### PR TITLE
End to end testing with playwright

### PR DESCRIPTION
**Pull request by Josh0104**
I created a folder tests that has a file where the code is testing if  
1. login works
2. user can create a project
3. user can delete the same project it created

I still need to make so the file will be able to read env variables, so if any of you guys know how that will be great, cause then it will be easy to setup Github Action. 

Also remind me to change the email and password of the dummy user, for security purpose of course :)

### CODE REVIEW

**Comment by Josh0104** [comment]
I could not use Deno with playwright so i used dotenv for the env variables

**Review by marc9622 — APPROVED** [review]
Shouldn't tests-examples be removed before merge?

**Comment by Josh0104** [comment]
> Shouldn't tests-examples be removed before merge?

Ohh yes forgot that my bad, will remove it now, thanks

**Comment by Josh0104** [comment]
> Shouldn't tests-examples be removed before merge?

Okay removed it

**Pull request merged**
